In [1]:
!python --version  #3.6.8

Python 3.6.8


In [2]:
import tensorflow as tf
tf.__version__

'1.15.0'

In [3]:
#only cpu is available right now because I have installed cuda and cudnn for different version of tensorflow. 
#This is one of the environment I have created for older version of tensorflow.
#To use GPU you need specific version of Cuda and cudnn

tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:

!nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243


In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

dataset_path = os.listdir('dataset')

room_types = os.listdir('dataset')
print (room_types)  #what kinds of rooms are in this dataset

print("Types of rooms found: ", len(dataset_path))



['bed_room', 'dining_room', 'living_room']
Types of rooms found:  3


In [6]:
rooms = []

for item in room_types:
 # Get all the file names
 all_rooms = os.listdir('dataset' + '/' +item)
 #print(all_rooms)

 # Add them to the list
 for room in all_rooms:
    rooms.append((item, str('dataset' + '/' +item) + '/' + room))
    print(rooms[:1])


[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_room', 'dataset/bed_room/apartment-2094734__340.jpg')]
[('bed_r

In [7]:
# Build a dataframe        
rooms_df = pd.DataFrame(data=rooms, columns=['room type', 'image'])
print(rooms_df.head())
print(rooms_df.tail())

  room type                                              image
0  bed_room        dataset/bed_room/apartment-2094734__340.jpg
1  bed_room        dataset/bed_room/apartment-4744139__340.jpg
2  bed_room     dataset/bed_room/architecture-2141065__340.jpg
3  bed_room  dataset/bed_room/architecture-modern-house-bea...
4  bed_room             dataset/bed_room/baby-1266117__340.jpg
       room type                                             image
388  living_room  dataset/living_room/victoria-borodinova-706.jpeg
389  living_room          dataset/living_room/wall-823611__340.jpg
390  living_room        dataset/living_room/woman-2099465__340.jpg
391  living_room         dataset/living_room/young-510440__340.jpg
392  living_room         dataset/living_room/young-510453__340.jpg


In [8]:
# Let's check how many samples for each category are present
print("Total number of rooms in the dataset: ", len(rooms_df))

Total number of rooms in the dataset:  393


In [9]:
room_count = rooms_df['room type'].value_counts()

print("rooms in each category: ")
print(room_count)

rooms in each category: 
bed_room       159
living_room    148
dining_room     86
Name: room type, dtype: int64


In [10]:
import cv2
path = 'dataset/'


im_size = 100

images = []
labels = []

for i in room_types:
    data_path = path + str(i)  # entered in 1st folder and then 2nd folder and then 3rd folder
    #filenames = [i for i in os.listdir(data_path) if i.endswith('.jpg')]
    filenames = [i for i in os.listdir(data_path) ]
   # print(filenames)  # will get the names of all images which ends with .jpg extension
    for f in filenames:
        img = cv2.imread(data_path + '/' + f)  # reading that image as array
        #print(img)  # will get the image as an array
        img = cv2.resize(img, (im_size, im_size))
        images.append(img)
        labels.append(i)

In [11]:
# Transform the image array to a numpy type

images = np.array(images)

images.shape

(393, 100, 100, 3)

In [12]:
images = images.astype('float32') / 255.0

In [13]:
images.shape

(393, 100, 100, 3)

In [14]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder


y=rooms_df['room type'].values
print(y[:5])

['bed_room' 'bed_room' 'bed_room' 'bed_room' 'bed_room']


In [15]:
!pip show tensorflow  #1.15.0


Name: tensorflow
Version: 1.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: d:\env_with_tensorflow1.14\myvenv\lib\site-packages
Requires: numpy, gast, google-pasta, tensorboard, tensorflow-estimator, termcolor, absl-py, keras-applications, wrapt, astor, opt-einsum, keras-preprocessing, grpcio, six, protobuf, wheel
Required-by: 


In [16]:
# for y

y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [17]:

y=y.reshape(-1,1)

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#Y=np.array(columnTransformer.fit_transform(y),dtype=np.str)
#Y=columnTransformer.fit_transform(y)


y = columnTransformer.fit_transform(y.tolist())
Y = y.astype('float64')


In [18]:

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


images, Y = shuffle(images, Y, random_state=1)

train_x, test_x, train_y, test_y = train_test_split(images, Y, test_size=0.05, random_state=415)

#inpect the shape of the training and testing.
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(373, 100, 100, 3)
(373, 3)
(20, 100, 100, 3)
(20, 3)


In [19]:
train_x=np.reshape(train_x,(373,30000))
print(train_x.shape)

test_x=np.reshape(test_x,(20,30000))
test_x.shape



(373, 30000)


(20, 30000)

In [20]:
# hyper Parameters
learning_rate = 0.001


In [21]:
# Network Parameters
n_hidden_1 = 256 # 1st layer has 256 neurons
n_hidden_2 = 256 # 2nd layer has 256 neurons
n_input = 30000 #  data input (img shape: 100*100*3)
n_classes = 3 # total classes (3)


In [22]:
import tensorflow as tf
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()

# tf Graph input
x = tf.placeholder("float", [None, n_input])
y_ = tf.placeholder("float", [None, n_classes])


In [23]:
# Store layers weight & bias
weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),  # n_input 30000 and n_hidden_1 256
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),  # output of h1 will be a input for h2 and n_hidden_2 256
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))  # 256,3
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

In [24]:
# Create model
def multilayer_perceptron(x, weights, biases):
    # Hidden layer with RELU activation
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])  #matmul on x and w , then adding it with bias # summation
    layer_1 = tf.nn.relu(layer_1)   # activation function
    
    # Hidden layer with RELU activation
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)
    
    # Output layer with linear activation
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    out_layer = tf.nn.softmax(out_layer)
    return out_layer


In [25]:
# Construct model
pred = multilayer_perceptron(x, weights, biases)


In [26]:
# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y_))   #. pred is the output of MLP . Y is the placeholder which will hold the target output
# cross-entropy for calculating error


optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)


Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [27]:
# Initializing the variables
init = tf.global_variables_initializer()
#create an empty list to store the cost history and accuracy history
cost_history = []
accuracy_history = []
# Launch the graph


In [28]:
# the execution
sess = tf.Session()
sess.run(init)

In [29]:
cost_history = []
n_epochs = 200

#ValueError: setting an array element with a sequence will resolve by 2 below given lines
#train_y=train_y.todense()
#print(train_y)


for i in range(n_epochs):
    a, c = sess.run([optimizer, cost], feed_dict={x: train_x, y_: train_y})  #working
    cost_history = np.append(cost_history,c)  # working
    print('epoch : ', i,  ' - ', 'cost: ', c) #working 
  

epoch :  0  -  cost:  1.318201
epoch :  1  -  cost:  1.3208818
epoch :  2  -  cost:  1.3208818
epoch :  3  -  cost:  1.3235629
epoch :  4  -  cost:  1.3235629
epoch :  5  -  cost:  1.3262215
epoch :  6  -  cost:  1.2458168
epoch :  7  -  cost:  1.1546621
epoch :  8  -  cost:  1.157343
epoch :  9  -  cost:  1.1546621
epoch :  10  -  cost:  1.1519811
epoch :  11  -  cost:  1.1466191
epoch :  12  -  cost:  1.1439382
epoch :  13  -  cost:  1.1439382
epoch :  14  -  cost:  1.1439382
epoch :  15  -  cost:  1.1439382
epoch :  16  -  cost:  1.1439382
epoch :  17  -  cost:  1.1439382
epoch :  18  -  cost:  1.1439382
epoch :  19  -  cost:  1.1439382
epoch :  20  -  cost:  1.1439382
epoch :  21  -  cost:  1.1439382
epoch :  22  -  cost:  1.1439382
epoch :  23  -  cost:  1.1439382
epoch :  24  -  cost:  1.1439382
epoch :  25  -  cost:  1.1439382
epoch :  26  -  cost:  1.1439382
epoch :  27  -  cost:  1.1439382
epoch :  28  -  cost:  1.1439382
epoch :  29  -  cost:  1.1439382
epoch :  30  -  cost: 

# checkig accuracy of model on test data


In [30]:


#test_y=test_y.todense()  #working solution of ValueError: setting an array element with a sequence.
print(test_y)


# toarray returns an ndarray; todense returns a matrix. If you want a matrix, use todense; otherwise, use toarray.


correct_prediction = tf.equal(tf.argmax(pred,1), tf.argmax(y_,1))   
correct_prediction 

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
accuracy


# retrun the accuracy on the test set.
print("Accuracy: ", sess.run(accuracy, feed_dict={x: test_x, y_:test_y}))

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
Accuracy:  0.35


# take input from user and predict the result

In [31]:

import cv2
img = cv2.imread('room_test_img.jpg')

img = cv2.resize(img, (100, 100))
#nx, ny, nc = 100,100,3
#img_flat = img.reshape(nx * ny * nc)
IMG = np.reshape(img,(1,30000))
pred_y = sess.run(pred, feed_dict={x: IMG}) 
print(pred_y)

[[1. 0. 0.]]


In [32]:
%%timeit -n1 -r1 
with tf.device('/CPU:0'):
    cpu_model =multilayer_perceptron(x, weights, biases)
    cpu_model

5.51 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
